### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [agilecrm/500apps-public-gtm-convertpath#2]
https://github.com/agilecrm/500apps-public-gtm-convertpath/blob/6cfc0324bad05aaa387c4cd9edc6173db3360cf9/template.tpl#L54

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by 500apps-RahulVangari** [comment]
@philpott 
![Screenshot Of Code in Template](https://user-images.githubusercontent.com/85161282/146777146-27b7bdd9-6888-41eb-ab1a-7d1a3af21554.png)
As you can see in the code we used encodeUriComponent for input query.
